blue_palette = ["#070D59", "#1F3C88", "#5893D4", "#CEDDEF", "#ebf0f6", "#98ccd3", "#364e68", "#132238"]
blue_inverted = ["#CEDDEF","#5893D4","#1F3C88","#070D59","#132238", "#364e68","#98ccd3","#ebf0f6"]

country_mappings = {
    'CEYLON': 'SRI LANKA', 
    'CEYLON (SRI LANKA)': 'SRI LANKA', 
    'ANDAMAN / NICOBAR ISLANDAS': 'ANDAMAN ISLANDS', 
    'Coast of AFRICA': 'AFRICA', 
    'RED SEA / INDIAN OCEAN': 'RED SEA', 
    'Between PORTUGAL & INDIA': 'UNKNOWN', 
    'SOLOMON ISLANDS / VANUATU': 'SOLOMON ISLANDS', 
    'UNITED ARAB EMIRATES (UAE)': 'UNITED ARAB EMIRATES', 
    'ITALY / CROATIA': 'ADRIATIC SEA',
    'ROATAN': 'HONDURAS', 
    'KOREA': 'SOUTH KOREA', 
    'ST. MAARTIN': 'ST. MARTIN', 
    'JAVA': 'INDONESIA', 
    'MID-PACIFC OCEAN': 'CENTRAL PACIFIC', 
    'WEST INDIES': 'CARIBBEAN SEA', 
    'BRITISH WEST INDIES': 'CARIBBEAN SEA', 
    'TOBAGO': 'TRINIDAD & TOBAGO', 
    'BRITISH ISLES': 'UNITED KINGDOM', 
    'EGYPT / ISRAEL': 'MEDITERRANEAN SEA', 
    'IRAN / IRAQ': 'IRAN',
    'PAPUA NEW GUINEA': 'NEW GUINEA',
    'BRITISH NEW GUINEA': 'NEW GUINEA',
    'EQUATORIAL GUINEA / CAMEROON': 'CAMEROON',
    'NETHERLANDS ANTILLES': 'CARIBBEAN SEA',
    'THE BALKANS': 'SLOVENIA',
    'ST HELENA, British overseas territory': 'ST HELENA',
    'GRAND CAYMAN': 'CAYMAN ISLANDS',
    'HONG KONG': 'CHINA',
    'TAIWAN': 'CHINA',
    'ENGLAND': 'UNITED KINGDOM',
    'IRELAND': 'UNITED KINGDOM',
    'SCOTLAND': 'UNITED KINGDOM',
    'FEDERATED STATES OF MICRONESIA': 'MICRONESIA',
    'REUNION ISLAND': 'REUNION',
    'NEW BRITAIN': 'NEW GUINEA',
    'MALDIVE ISLANDS': 'MALDIVES',
    'WESTERN SAMOA': 'SAMOA',
    'SAN DOMINGO': 'DOMINICAN REPUBLIC',
    'PHILLIPINES': 'PHILIPPINES',
    'COLUMBIA': 'COLOMBIA', 
    'OKINAWA': 'JAPAN',
    'FALKLAND ISLANDS': 'ARGENTINA',
    'CRETE': 'GREECE',
    'BAHREIN': 'BAHRAIN'
}

month_mapping = {
    'Jan': 1,
    'Feb': 2, 
    'Mar': 3,
    'Ap': 4,
    'Apr': 4,
    'May': 5,
    'Jun': 6,
    'June': 6,
    'Jul': 7,
    'July': 7,
    'Aug': 8,
    'Sep': 9,
    'Oct': 10,
    'Nov': 11,
    'Dec': 12
}

region_mappings = {
    'AUSTRALIA': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'SRI LANKA': {'region': 'ASIA', 'hemisphere': 'N'},
    'BANGLADESH': {'region': 'ASIA', 'hemisphere': 'N'},
    'MALAYSIA': {'region': 'ASIA', 'hemisphere': 'N'},
    'CHINA': {'region': 'ASIA', 'hemisphere': 'N'},
    'JAPAN': {'region': 'ASIA', 'hemisphere': 'N'},
    'UNITED KINGDOM': {'region': 'EUROPE', 'hemisphere': 'N'},
    'PHILIPPINES': {'region': 'ASIA', 'hemisphere': 'N'},
    'INDONESIA': {'region': 'ASIA', 'hemisphere': 'C'},
    'THAILAND': {'region': 'ASIA', 'hemisphere': 'N'},
    'USA': {'region': 'NORTH AMERICA', 'hemisphere': 'N'},
    'MEXICO': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'PANAMA': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'PERU': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'BRAZIL': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'SOUTH AFRICA': {'region': 'SOUTHERN AFRICA', 'hemisphere': 'S'},
    'COSTA RICA': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'MALDIVES': {'region': 'INDIAN OCEAN', 'hemisphere': 'N'},
    'BAHAMAS': {'region': 'CARIBBEAN','hemisphere': 'N'},
    'NEW CALEDONIA': {'region': 'SOUTH PACIFIC','hemisphere': 'S'},
    'ECUADOR': {'region': 'SOUTH AMERICA', 'hemisphere': 'N'},
    'LIBYA': {'region': 'NORTHERN AFRICA','hemisphere': 'N'},
    'CUBA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'MAURITIUS': {'region': 'INDIAN OCEAN', 'hemisphere': 'S'},
    'NEW ZEALAND': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'SPAIN': {'region': 'EUROPE', 'hemisphere': 'N'},
    'SAMOA': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'SOLOMON ISLANDS': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'JAPAN': {'region': 'ASIA', 'hemisphere': 'N'},
    'EGYPT': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'ST HELENA': {'region': 'SOUTH ATLANTIC', 'hemisphere': 'S'},
    'COMOROS': {'region': 'INDIAN OCEAN', 'hemisphere': 'S'},
    'REUNION': {'region': 'INDIAN OCEAN', 'hemisphere': 'S'},
    'FRENCH POLYNESIA': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'UNITED ARAB EMIRATES': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'COLOMBIA': {'region': 'SOUTH AMERICA', 'hemisphere': 'N'},
    'CAPE VERDE': {'region': 'NORTH ATLANTIC', 'hemisphere': 'N'},
    'FIJI': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'DOMINICAN REPUBLIC': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'GABON': {'region': 'CENTRAL AFRICA','hemisphere': 'C'},
    'CAYMAN ISLANDS': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'ARUBA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'MOZAMBIQUE': {'region': 'SOUTHERN AFRICA', 'hemisphere': 'S'},
    'PUERTO RICO': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'ITALY': {'region': 'EUROPE', 'hemisphere': 'N'},
    'GREECE': {'region': 'EUROPE', 'hemisphere': 'N'},
    'ST. MARTIN': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'FRANCE': {'region': 'EUROPE', 'hemisphere': 'N'},
    'NEW GUINEA': {'region': 'SOUTH PACIFIC', 'hemisphere': 'N'},
    'TRINIDAD & TOBAGO': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'KIRIBATI': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'ISRAEL': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'DIEGO GARCIA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'JAMAICA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'PALESTINIAN TERRITORIES': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'GUAM': {'region': 'NORTH PACIFIC', 'hemisphere': 'N'},
    'SEYCHELLES': {'region': 'INDIAN OCEAN', 'hemisphere': 'S'},
    'BELIZE': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'NIGERIA': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'TONGA': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'CANADA': {'region': 'NORTH AMERICA', 'hemisphere': 'N'},
    'CROATIA': {'region': 'EUROPE', 'hemisphere': 'N'},
    'SAUDI ARABIA': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'CHILE': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'ANTIGUA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'KENYA': {'region': 'CENTRAL AFRICA', 'hemisphere': 'C'},
    'RUSSIA': {'region': 'EUROPE', 'hemisphere': 'N'},
    'TURKS & CAICOS': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'AZORES': {'region': 'NORTH ATLANTIC', 'hemisphere': 'N'},
    'SOUTH KOREA': {'region': 'ASIA', 'hemisphere': 'N'},
    'MALTA': {'region': 'MEDITERRANEAN SEA', 'hemisphere': 'N'},
    'VIETNAM': {'region': 'ASIA', 'hemisphere': 'N'},
    'MADAGASCAR': {'region': 'SOUTHERN AFRICA', 'hemisphere': 'S'},
    'PANAMA': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'SOMALIA': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'NEVIS': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'BRITISH VIRGIN ISLANDS': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'NORWAY': {'region': 'EUROPE', 'hemisphere': 'N'},
    'SENEGAL': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'YEMEN': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'GULF OF ADEN': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'SIERRA LEONE': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'LIBERIA': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'VANUATU': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'HONDURAS': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'VENEZUELA': {'region': 'SOUTH AMERICA', 'hemisphere': 'N'},
    'SRI LANKA': {'region': 'ASIA', 'hemisphere': 'N'},
    'URUGUAY': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'INDIA': {'region': 'ASIA', 'hemisphere': 'N'},
    'MICRONESIA': {'region': 'NORTH PACIFIC', 'hemisphere': 'N'},
    'CARIBBEAN SEA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'OKINAWA': {'region': 'ASIA', 'hemisphere': 'N'},
    'TANZANIA': {'region': 'SOUTHERN AFRICA', 'hemisphere': 'S'},
    'MARSHALL ISLANDS': {'region': 'NORTH PACIFIC', 'hemisphere': 'N'},
    'MEDITERRANEAN SEA': {'region': 'MEDITERRANEAN SEA', 'hemisphere': 'N'},
    'NORTHERN ARABIAN SEA': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'EL SALVADOR': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'ANGOLA': {'region': 'SOUTHERN AFRICA', 'hemisphere': 'S'},
    'BERMUDA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'MONTENEGRO': {'region': 'EUROPE', 'hemisphere': 'N'},
    'IRAN': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'TUNISIA': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'NAMIBIA': {'region': 'SOUTHERN AFRICA', 'hemisphere': 'S'},
    'NORTH ATLANTIC OCEAN': {'region': 'NORTH ATLANTIC', 'hemisphere': 'N'},
    'PORTUGAL': {'region': 'EUROPE', 'hemisphere': 'N'},
    'SOUTH CHINA SEA': {'region': 'ASIA', 'hemisphere': 'N'},
    'BANGLADESH': {'region': 'ASIA', 'hemisphere': 'N'},
    'PALAU': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'GRENADA': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'IRAQ': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'TURKEY': {'region': 'EUROPE', 'hemisphere': 'N'},
    'SINGAPORE': {'region': 'ASIA', 'hemisphere': 'N'},
    'SUDAN': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'JOHNSTON ISLAND': {'region': 'NORTH PACIFIC', 'hemisphere': 'N'},
    'SOUTH PACIFIC OCEAN': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'RED SEA': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'NORTH PACIFIC OCEAN': {'region': 'NORTH PACIFIC', 'hemisphere': 'N'},
    'ADMIRALTY ISLANDS': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'SOUTH ATLANTIC OCEAN': {'region': 'SOUTH ATLANTIC', 'hemisphere': 'S'},
    'PERSIAN GULF': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'NORTH SEA': {'region': 'EUROPE', 'hemisphere': 'N'},
    'NICARAGUA': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'AMERICAN SAMOA': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'ANDAMAN ISLANDS': {'region': 'INDIAN OCEAN', 'hemisphere': 'N'},
    'GABON': {'region': 'SOUTHERN AFRICA', 'hemisphere': 'S'},
    'MAYOTTE': {'region': 'INDIAN OCEAN', 'hemisphere': 'S'},
    'SLOVENIA': {'region': 'EUROPE', 'hemisphere': 'N'},
    'ARGENTINA': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'MARTINIQUE': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'GUATEMALA': {'region': 'CENTRAL AMERICA', 'hemisphere': 'N'},
    'NORTHERN MARIANA ISLANDS': {'region': 'NORTH PACIFIC', 'hemisphere': 'N'},
    'SOUTHWEST PACIFIC OCEAN': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'BAY OF BENGAL': {'region': 'INDIAN OCEAN', 'hemisphere': 'N'},
    'CURACAO': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'ICELAND': {'region': 'EUROPE', 'hemisphere': 'N'},
    'ADRIATIC SEA': {'region': 'MEDITERRANEAN SEA', 'hemisphere': 'N'},
    'BARBADOS': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'MONACO': {'region': 'EUROPE', 'hemisphere': 'N'},
    'GUYANA': {'region': 'SOUTH AMERICA', 'hemisphere': 'N'},
    'HAITI': {'region': 'CARIBBEAN', 'hemisphere': 'N'},
    'KUWAIT': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'FALKLAND ISLANDS': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'CRETE': {'region': 'MEDITERRANEAN SEA', 'hemisphere': 'N'},
    'CYPRUS': {'region': 'MEDITERRANEAN SEA', 'hemisphere': 'N'},
    'BURMA': {'region': 'ASIA', 'hemisphere': 'N'},
    'LEBANON': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'PARAGUAY': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'GEORGIA': {'region': 'EUROPE', 'hemisphere': 'N'},
    'SYRIA': {'region': 'MIDDLE EAST', 'hemisphere': 'N'},
    'TUVALU': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'GUINEA': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'CAMEROON': {'region': 'CENTRAL AFRICA', 'hemisphere': 'C'},
    'COOK ISLANDS': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'PERU': {'region': 'SOUTH AMERICA', 'hemisphere': 'S'},
    'ALGERIA': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'TASMAN SEA': {'region': 'SOUTH PACIFIC', 'hemisphere': 'S'},
    'GHANA': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'GREENLAND': {'region': 'NORTH AMERICA', 'hemisphere': 'N'},
    'SWEDEN': {'region': 'EUROPE', 'hemisphere': 'N'},
    'DJIBOUTI': {'region': 'NORTHERN AFRICA', 'hemisphere': 'N'},
    'BAHREIN': {'region': 'MIDDLE EAST', 'hemisphere': 'N'}
}


